trigger:
- master

pool: MyAgent

variables:
 myResourceGroupName: ArielResourceGroup
 subscriptionName: "MSEC_Candidates_Homeworks"
 subscriptionID: "a8108c2b-496c-424d-8347-ecc8afb6384c"
 location: "eastus"

steps:
- script: hostname

- task: AzurePowerShell@5
  inputs:
    ScriptType: 'InlineScript'
    Inline: |
      Get-AzLocation | select Location
            $location = "eastus"
            $resourceGroup = "ArielResourceGroup"
            New-AzResourceGroup -Name $resourceGroup -Location $location

- task: AzurePowerShell@5
  inputs:
    ScriptType: 'InlineScript'
    Inline: |
      New-AzResourceGroupDeployment -Name storageaccount_A `
           -ResourceGroupName $resourceGroup `
           -TemplateFile 'azuredeploy.json' `
           -TemplateParameterFile 'azuredeploy.parameters.json'







