trigger:
- master

pool: MyAgent
 
steps:

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Get-AzLocation | select Location
      $location = "eastus"
      $resourceGroup = "ArielResourceGroup"
      New-AzResourceGroup -Name $resourceGroup -Location $location
      
#Create an ARM (Azure Resource Manager) template for storage account and create 2 storage accounts
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
     New-AzResourceGroupDeployment -Name storageaccount_A `
     -ResourceGroupName $resourceGroup `
     -TemplateFile 'azuredeploy.json' `
     -TemplateParameterFile 'azuredeploy.parameters.json'

#Create an ARM template for a Windows 
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      New-AzResourceGroupDeployment `
      -Name Deployment_VM `
      -ResourceGroupName $resourceGroup `
      -TemplateFile 'windowsServer.json'
      
#create, upload and copy 100 blobs from Storage account A to B,execute it on the server
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $SubscriptionID= "a8108c2b-496c-424d-8347-ecc8afb6384c"
      Set-AzContext -Subscription $SubscriptionID 
            $result = Invoke-AzVMRunCommand `
             -ResourceGroupName $resourceGroup `
             -VMName simple-vm `
             -CommandId RunPowerShellScript `
             -ScriptPath C:\Users\ariel\Microsoft.Azure\Blobs.ps1
  
  #metric
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $resourceId1 = "/subscriptions/a8108c2b-496c-424d-8347-ecc8afb6384c/resourceGroups/ArielResourceGroup/providers/Microsoft.Storage/storageAccounts/arielstoragesccount1"
       Get-AzMetricDefinition -ResourceId $resourceId1
        Get-AzMetric -ResourceId $resourceId1 -MetricNames "UsedCapacity" -TimeGrain 01:00:00
      
      $resourceId2 = "/subscriptions/a8108c2b-496c-424d-8347-ecc8afb6384c/resourceGroups/ArielResourceGroup/providers/Microsoft.Storage/storageAccounts/arielstorageaccount2"
       Get-AzMetricDefinition -ResourceId $resourceId2
         Get-AzMetric -ResourceId $resourceId2 -MetricNames "UsedCapacity" -TimeGrain 01:00:00
         




