trigger:
- master

pool: MyAgent

variables:
 myResourceGroupName: ArielResourceGroup
 subscriptionName: "MSEC_Candidates_Homeworks"
 subscriptionID: "a8108c2b-496c-424d-8347-ecc8afb6384c"
 location: "eastus"
 
steps:
- script: hostname

- task: GitHubComment@0
  inputs:
    gitHubConnection: 'github.com/Ariel-David'
    repositoryName: 'Ariel-David/Microsoft_Azure'


- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 
     New-AzResourceGroupDeployment -ResourceGroupName ArielResourceGroup -TemplateFile azuredeploy.json
     
     
    



