trigger:
- master

pool: MyAgent

variables:
 myResourceGroupName: ArielResourceGroup
 subscriptionName: "MSEC_Candidates_Homeworks"
 subscriptionID: "a8108c2b-496c-424d-8347-ecc8afb6384c"
 location: "eastus"
 
steps:

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Get-AzLocation | select Location
      $location = "eastus"
      $resourceGroup = "ArielResourceGroup"
      New-AzResourceGroup -Name $resourceGroup -Location $location
      
#Create an ARM (Azure Resource Manager) template for storage account and create 2 storage accounts
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
     New-AzResourceGroupDeployment -Name storageaccount_A `
     -ResourceGroupName $resourceGroup `
     -TemplateFile 'azuredeploy.json' `
     -TemplateParameterFile 'azuredeploy.parameters.json'

#Create an ARM template for a Windows 
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      New-AzResourceGroupDeployment `
      -Name Deployment_VM `
      -ResourceGroupName $resourceGroup `
      -TemplateFile 'windowsServer.json'






