trigger:
- master

pool: MyAgent

variables:
 myResourceGroupName: ArielResourceGroup
 subscriptionName: "MSEC_Candidates_Homeworks"
 subscriptionID: "a8108c2b-496c-424d-8347-ecc8afb6384c"
 location: "eastus"
 
steps:
- script: hostname

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'az storage account create --name arielstorageaccount4 --resource-group ArielResourceGroup --kind StorageV2 --location eastus'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $resourceGroup = "myResourceGroup1"
      New-AzResourceGroup -Name $resourceGroup -Location $location
      $storageAccount = New-AzStorageAccount -ResourceGroupName $resourceGroup `
        -Name "mystorageaccount1" `
        -SkuName Standard_LRS `
        -Location $location `
      
      $ctx = $storageAccount.Context
      $storageAccount = New-AzStorageAccount -ResourceGroupName $resourceGroup `
        -Name "mystorageaccount2" `
        -SkuName Standard_LRS `
        -Location $location `
      
      $ctx = $storageAccount.Context

